name: Build static Linux binary

on:
  workflow_dispatch:

jobs:
  build-static-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-musl

    - name: Install musl tools
      run: sudo apt update && sudo apt install -y musl-tools

    - name: Build static binary
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"
      run: |
        cargo build --release --target x86_64-unknown-linux-musl

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: lll-linux-static
        path: target/x86_64-unknown-linux-musl/release/lll
