name: Build Linux binary

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y m4 g++ libgmp-dev libmpfr-dev pkg-config
    - name: Build binary
      run: cargo build --release

    - name: Archive binary
      run: tar -czvf lll-linux.tar.gz -C target/release lll

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lll-linux
        path: lll-linux.tar.gz
