name: Build static Linux binary

on:
  workflow_dispatch:

jobs:
  build-static:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install musl target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Install musl tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Build static binary
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"
      run: |
        cargo build --release --target x86_64-unknown-linux-musl
        strip target/x86_64-unknown-linux-musl/release/lll
        tar -czvf lll-linux-static.tar.gz -C target/x86_64-unknown-linux-musl/release lll

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: lll-linux-static
        path: lll-linux-static.tar.gz
