
name: Build LLL for Windows (GNU)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust and GNU target
      run: |
        rustup default stable
        rustup target add x86_64-pc-windows-gnu

    - name: Build release for Windows GNU
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: lll-windows
        path: target/x86_64-pc-windows-gnu/release/lll.exe