name: Cross-compile to Windows (.exe)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cross
      run: cargo install cross

    - name: Build for Windows using cross
      run: cross build --release --target x86_64-pc-windows-gnu

    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: lll-windows
        path: target/x86_64-pc-windows-gnu/release/lll.exe
